name: caes-py3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.3
    - CoolProp=6.3.0
    - pandas=1.0.5
    - numpy=1.18.5
    - seaborn=0.11.0
    - matplotlib=3.3.3
    - scipy=1.5.0
    - joblib=0.16.0
    - xlrd=1.2.0